# Generated by Django 4.0.6 on 2022-08-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_followers_user_ranking_user_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
