# Generated by Django 4.0.6 on 2022-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
