# Generated by Django 4.0.6 on 2022-08-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_feed_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_image', models.TextField()),
                ('region', models.TextField()),
                ('participant', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
