# Generated by Django 4.0.6 on 2022-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_volunteeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeritem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
