# Generated by Django 4.0.6 on 2022-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_volunteeritem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeritem',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
