# Generated by Django 4.0.6 on 2022-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_volunteeritem_date_alter_volunteeritem_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeritem',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='volunteeritem',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
