# Generated by Django 4.0.6 on 2022-08-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_volunteeritem_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeritem',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
