# Generated by Django 4.0.6 on 2022-08-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_volunteeritem_grant_participateitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeritem',
            name='participate_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.participateitems'),
            preserve_default=False,
        ),
    ]
