# Generated by Django 4.0.6 on 2022-08-06 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0015_alter_volunteeritem_participate_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateitems',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
