# Generated by Django 4.0.6 on 2022-08-06 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0016_alter_participateitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeritem',
            name='participate_items',
        ),
        migrations.AddField(
            model_name='volunteeritem',
            name='participate_items',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ParticipateItems',
        ),
    ]
