# Generated by Django 4.0.6 on 2022-08-08 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_volunteeritem_participate_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 2, 28, 895590)),
        ),
        migrations.AddField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 2, 28, 896907)),
        ),
    ]
