# Generated by Django 4.0.6 on 2022-08-08 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_feed_create_time_volunteeritem_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeritem',
            name='admit_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 34, 22, 320358)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 34, 22, 320358)),
        ),
    ]
