# Generated by Django 4.0.6 on 2022-08-08 04:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0019_volunteeritem_admit_time_alter_feed_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeritem',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='volunteeritem',
            name='participate_items',
        ),
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 53, 46, 696211)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 53, 46, 696211)),
        ),
        migrations.CreateModel(
            name='ParticipateItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteerItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.volunteeritem')),
            ],
        ),
    ]
