# Generated by Django 4.0.6 on 2022-08-25 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_feed_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 14, 32, 24, 470488)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 14, 32, 24, 471708)),
        ),
    ]
