# Generated by Django 4.1 on 2022-08-14 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_alter_feed_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 14, 16, 54, 21, 25759)
            ),
        ),
        migrations.AlterField(
            model_name="volunteeritem",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 14, 16, 54, 21, 26756)
            ),
        ),
    ]
