# Generated by Django 4.1 on 2022-08-25 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_alter_feed_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 25, 15, 21, 59, 839576)
            ),
        ),
        migrations.AlterField(
            model_name="volunteeritem",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 25, 15, 21, 59, 840572)
            ),
        ),
    ]
