# Generated by Django 4.0.6 on 2022-08-26 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_feed_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participateitems',
            name='volunteerItem',
        ),
        migrations.AddField(
            model_name='volunteeritem',
            name='participate_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.participateitems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 37, 15, 308484)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 37, 15, 309482)),
        ),
    ]
