# Generated by Django 4.0.6 on 2022-08-26 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_participateitems_volunteeritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 38, 38, 515622)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 38, 38, 516615)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='participate_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.participateitems'),
        ),
    ]
