# Generated by Django 4.0.6 on 2022-08-26 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_feed_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeritem',
            name='participate_item',
        ),
        migrations.AddField(
            model_name='participateitems',
            name='volunteerItem',
            field=models.ManyToManyField(to='content.volunteeritem'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 45, 51, 729892)),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 45, 51, 730889)),
        ),
    ]
