# Generated by Django 4.0.6 on 2022-08-26 08:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0028_remove_volunteeritem_participate_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 48, 29, 591023)),
        ),
        migrations.RemoveField(
            model_name='participateitems',
            name='user',
        ),
        migrations.AddField(
            model_name='participateitems',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteeritem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 48, 29, 592011)),
        ),
    ]
